opentelemetry-operator:
  manager:
    extraArgs:
      - --enable-go-instrumentation
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
      recreate: true
crds:
  create: true
defaultCRConfig:
  image:
    repository: "docker.elastic.co/elastic-agent/elastic-agent"
    tag: "9.1.2"
  targetAllocator:
    enabled: false
clusterRole:
  rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get"]

collectors:
  cluster:
    enabled: false
  daemon:
    fullnameOverride: "opentelemetry-kube-stack-daemon"
    env:
      - name: ELASTIC_AGENT_OTEL
        value: '"true"'
    presets:
      kubeletMetrics:
        enabled: false
      hostMetrics:
        enabled: false
      logsCollection:
        enabled: true
        storeCheckpoints: true
    scrape_configs_file: ""
    config:
      exporters:
        otlp/gateway:
          endpoint: "http://REPLACE_WITH_IP:4317"
          tls:
            insecure: true
      processors:
        batch: {}
        resourcedetection/eks:
          detectors: [env, eks]
          timeout: 15s
          override: true
          eks:
            resource_attributes:
              k8s.cluster.name:
                enabled: true
        resourcedetection/gcp:
          detectors: [env, gcp]
          timeout: 2s
          override: true
        resourcedetection/aks:
          detectors: [env, aks]
          timeout: 2s
          override: true
          aks:
            resource_attributes:
              k8s.cluster.name:
                enabled: true
        resource/hostname:
          attributes:
            - key: host.name
              from_attribute: k8s.node.name
              action: upsert
        resourcedetection/system:
          detectors: ["system", "ec2"]
          system:
            hostname_sources: ["os"]
            resource_attributes:
              host.name:
                enabled: true
              host.id:
                enabled: false
              host.arch:
                enabled: true
              host.ip:
                enabled: true
              host.mac:
                enabled: true
              host.cpu.vendor.id:
                enabled: true
              host.cpu.family:
                enabled: true
              host.cpu.model.id:
                enabled: true
              host.cpu.model.name:
                enabled: true
              host.cpu.stepping:
                enabled: true
              host.cpu.cache.l2.size:
                enabled: true
              os.description:
                enabled: true
              os.type:
                enabled: true
          ec2:
            resource_attributes:
              host.name:
                enabled: false
              host.id:
                enabled: true
        resource/cloud:
          attributes:
            - key: cloud.instance.id
              from_attribute: host.id
              action: insert
        k8sattributes:
          filter:
            node_from_env_var: OTEL_K8S_NODE_NAME
          passthrough: false
          pod_association:
            - sources:
                - from: resource_attribute
                  name: k8s.pod.ip
            - sources:
                - from: resource_attribute
                  name: k8s.pod.uid
            - sources:
                - from: connection
          extract:
            metadata:
              - "k8s.namespace.name"
              - "k8s.deployment.name"
              - "k8s.replicaset.name"
              - "k8s.statefulset.name"
              - "k8s.daemonset.name"
              - "k8s.cronjob.name"
              - "k8s.job.name"
              - "k8s.node.name"
              - "k8s.pod.name"
              - "k8s.pod.ip"
              - "k8s.pod.uid"
              - "k8s.pod.start_time"
              - "service.name"
              - "service.version"
      receivers:
        otlp: null
        filelog:
          exclude:
            - /var/log/pods/*opentelemetry-kube-stack*/*/*.log
      service:
        pipelines:
          logs: null
          metrics: null
          traces: null
          logs/node:
            receivers:
              - filelog
            processors:
              - batch
              - k8sattributes
              - resourcedetection/system
              - resourcedetection/eks
              - resourcedetection/gcp
              - resourcedetection/aks
              - resource/hostname
              - resource/cloud
            exporters:
              - otlp/gateway

  gateway:
    fullnameOverride: "opentelemetry-kube-stack-gateway"
    suffix: gateway
    replicas: 1
    enabled: true
    env:
      - name: ELASTIC_AGENT_OTEL
        value: '"true"'
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ELASTIC_OTLP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: elastic-secret-otel
            key: elastic_otlp_endpoint
      - name: ELASTIC_API_KEY
        valueFrom:
          secretKeyRef:
            name: elastic-secret-otel
            key: elastic_api_key
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
      processors:
        batch:
          send_batch_size: 1000
          timeout: 1s
          send_batch_max_size: 1500
      exporters:
        otlp/ingest:
          endpoint: ${env:ELASTIC_OTLP_ENDPOINT}
          headers:
            Authorization: ApiKey ${env:ELASTIC_API_KEY}
          timeout: 15s
      service:
        pipelines:
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/ingest]

instrumentation:
  name: elastic-instrumentation
  enabled: false